// default package
// Generated 3-nov-2017 12.16.15 by Hibernate Tools 5.2.5.Final

/**
 * Ap generated by hbm2java
 */
public class Ap implements java.io.Serializable {

	private String mac;
	private int canale;
	private String ssid;

	public Ap() {
	}

	public Ap(String mac, int canale, String ssid) {
		this.mac = mac;
		this.canale = canale;
		this.ssid = ssid;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public int getCanale() {
		return this.canale;
	}

	public void setCanale(int canale) {
		this.canale = canale;
	}

	public String getSsid() {
		return this.ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}

}
