package hibernategenerato;
// default package
// Generated 8-nov-2017 11.08.49 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Campus generated by hbm2java
 */
public class Campus implements java.io.Serializable {

	private Integer id;
	private Utente utente;
	private String nome;
	private Set edificios = new HashSet(0);

	public Campus() {
	}

	public Campus(Utente utente, String nome) {
		this.utente = utente;
		this.nome = nome;
	}

	public Campus(Utente utente, String nome, Set edificios) {
		this.utente = utente;
		this.nome = nome;
		this.edificios = edificios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getEdificios() {
		return this.edificios;
	}

	public void setEdificios(Set edificios) {
		this.edificios = edificios;
	}

}
