// default package
// Generated 3-nov-2017 12.16.15 by Hibernate Tools 5.2.5.Final

/**
 * Edificio generated by hbm2java
 */
public class Edificio implements java.io.Serializable {

	private String nome;
	private String università;

	public Edificio() {
	}

	public Edificio(String nome, String università) {
		this.nome = nome;
		this.università = università;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getUniversità() {
		return this.università;
	}

	public void setUniversità(String università) {
		this.università = università;
	}

}
