// default package
// Generated 3-nov-2017 12.16.15 by Hibernate Tools 5.2.5.Final

/**
 * Informazioni generated by hbm2java
 */
public class Informazioni implements java.io.Serializable {

	private Integer id;
	private String dati;
	private String informazionicol;

	public Informazioni() {
	}

	public Informazioni(String dati, String informazionicol) {
		this.dati = dati;
		this.informazionicol = informazionicol;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDati() {
		return this.dati;
	}

	public void setDati(String dati) {
		this.dati = dati;
	}

	public String getInformazionicol() {
		return this.informazionicol;
	}

	public void setInformazionicol(String informazionicol) {
		this.informazionicol = informazionicol;
	}

}
