// default package
// Generated 3-nov-2017 12.16.15 by Hibernate Tools 5.2.5.Final

/**
 * Notifiche generated by hbm2java
 */
public class Notifiche implements java.io.Serializable {

	private Integer id;
	private String dati;

	public Notifiche() {
	}

	public Notifiche(String dati) {
		this.dati = dati;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDati() {
		return this.dati;
	}

	public void setDati(String dati) {
		this.dati = dati;
	}

}
