// default package
// Generated 3-nov-2017 12.16.15 by Hibernate Tools 5.2.5.Final

/**
 * StanzaHasNotifiche generated by hbm2java
 */
public class StanzaHasNotifiche implements java.io.Serializable {

	private StanzaHasNotificheId id;

	public StanzaHasNotifiche() {
	}

	public StanzaHasNotifiche(StanzaHasNotificheId id) {
		this.id = id;
	}

	public StanzaHasNotificheId getId() {
		return this.id;
	}

	public void setId(StanzaHasNotificheId id) {
		this.id = id;
	}

}
