// default package
// Generated 3-nov-2017 12.16.15 by Hibernate Tools 5.2.5.Final

/**
 * StanzaHasAp generated by hbm2java
 */
public class StanzaHasAp implements java.io.Serializable {

	private StanzaHasApId id;

	public StanzaHasAp() {
	}

	public StanzaHasAp(StanzaHasApId id) {
		this.id = id;
	}

	public StanzaHasApId getId() {
		return this.id;
	}

	public void setId(StanzaHasApId id) {
		this.id = id;
	}

}
