// default package
// Generated 3-nov-2017 12.16.15 by Hibernate Tools 5.2.5.Final

/**
 * StanzaHasNotificheId generated by hbm2java
 */
public class StanzaHasNotificheId implements java.io.Serializable {

	private String stanzaNome;
	private String stanzaEdificioNome;
	private int notificheId;

	public StanzaHasNotificheId() {
	}

	public StanzaHasNotificheId(String stanzaNome, String stanzaEdificioNome, int notificheId) {
		this.stanzaNome = stanzaNome;
		this.stanzaEdificioNome = stanzaEdificioNome;
		this.notificheId = notificheId;
	}

	public String getStanzaNome() {
		return this.stanzaNome;
	}

	public void setStanzaNome(String stanzaNome) {
		this.stanzaNome = stanzaNome;
	}

	public String getStanzaEdificioNome() {
		return this.stanzaEdificioNome;
	}

	public void setStanzaEdificioNome(String stanzaEdificioNome) {
		this.stanzaEdificioNome = stanzaEdificioNome;
	}

	public int getNotificheId() {
		return this.notificheId;
	}

	public void setNotificheId(int notificheId) {
		this.notificheId = notificheId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StanzaHasNotificheId))
			return false;
		StanzaHasNotificheId castOther = (StanzaHasNotificheId) other;

		return ((this.getStanzaNome() == castOther.getStanzaNome()) || (this.getStanzaNome() != null
				&& castOther.getStanzaNome() != null && this.getStanzaNome().equals(castOther.getStanzaNome())))
				&& ((this.getStanzaEdificioNome() == castOther.getStanzaEdificioNome())
						|| (this.getStanzaEdificioNome() != null && castOther.getStanzaEdificioNome() != null
								&& this.getStanzaEdificioNome().equals(castOther.getStanzaEdificioNome())))
				&& (this.getNotificheId() == castOther.getNotificheId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStanzaNome() == null ? 0 : this.getStanzaNome().hashCode());
		result = 37 * result + (getStanzaEdificioNome() == null ? 0 : this.getStanzaEdificioNome().hashCode());
		result = 37 * result + this.getNotificheId();
		return result;
	}

}
