-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 12:04:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema indoorlocalizer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `indoorlocalizer` ;

-- -----------------------------------------------------
-- Schema indoorlocalizer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indoorlocalizer` DEFAULT CHARACTER SET utf8mb4 ;
USE `indoorlocalizer` ;

-- -----------------------------------------------------
-- Table `indoorlocalizer`.`ap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`ap` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`ap` (
  `mac` VARCHAR(255) NOT NULL,
  `canale` INT NOT NULL,
  `ssid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`mac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`edificio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`edificio` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`edificio` (
  `nome` VARCHAR(255) NOT NULL,
  `università` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nome`),
  UNIQUE INDEX `università_UNIQUE` (`università` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`informazioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`informazioni` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`informazioni` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dati` TEXT NULL,
  `informazionicol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`stanza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`stanza` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`stanza` (
  `nome` VARCHAR(255) NOT NULL,
  `edificio_nome` VARCHAR(255) NOT NULL,
  `piano` INT NULL,
  `informazioni_id` INT NULL,
  PRIMARY KEY (`nome`, `edificio_nome`),
  INDEX `fk_stanza_edificio_idx` (`edificio_nome` ASC),
  INDEX `fk_stanza_informazioni1_idx` (`informazioni_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`stanza_has_ap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`stanza_has_ap` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`stanza_has_ap` (
  `stanza_nome` VARCHAR(255) NOT NULL,
  `stanza_edificio_nome` VARCHAR(255) NOT NULL,
  `ap_mac` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`stanza_nome`, `stanza_edificio_nome`, `ap_mac`),
  INDEX `fk_stanza_has_ap_ap1_idx` (`ap_mac` ASC),
  INDEX `fk_stanza_has_ap_stanza1_idx` (`stanza_nome` ASC, `stanza_edificio_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`notifiche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`notifiche` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`notifiche` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dati` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`utente` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`utente` (
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cognome` VARCHAR(255) NOT NULL,
  `pwd` TEXT NOT NULL,
  `abilitato` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`stanza_has_notifiche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`stanza_has_notifiche` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`stanza_has_notifiche` (
  `stanza_nome` VARCHAR(255) NOT NULL,
  `stanza_edificio_nome` VARCHAR(255) NOT NULL,
  `notifiche_id` INT NOT NULL,
  PRIMARY KEY (`stanza_nome`, `stanza_edificio_nome`, `notifiche_id`),
  INDEX `fk_stanza_has_notifiche_notifiche1_idx` (`notifiche_id` ASC),
  INDEX `fk_stanza_has_notifiche_stanza1_idx` (`stanza_nome` ASC, `stanza_edificio_nome` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
