-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 16:50:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema indoorlocalizer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `indoorlocalizer` ;

-- -----------------------------------------------------
-- Schema indoorlocalizer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indoorlocalizer` DEFAULT CHARACTER SET utf8mb4 ;
USE `indoorlocalizer` ;

-- -----------------------------------------------------
-- Table `indoorlocalizer`.`utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`utente` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`utente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cognome` VARCHAR(255) NOT NULL,
  `pwd` TEXT NOT NULL,
  `abilitato` TINYINT NOT NULL DEFAULT 1,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`ap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`ap` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`ap` (
  `mac` VARCHAR(255) NOT NULL,
  `canale` INT NOT NULL,
  `ssid` VARCHAR(255) NOT NULL,
  `utente_id` INT NOT NULL,
  PRIMARY KEY (`mac`),
  INDEX `fk_ap_utente1_idx` (`utente_id` ASC),
  CONSTRAINT `fk_ap_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `indoorlocalizer`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`campus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`campus` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`campus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `utente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `fk_campus_utente1_idx` (`utente_id` ASC),
  CONSTRAINT `fk_campus_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `indoorlocalizer`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`edificio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`edificio` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`edificio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `utente_id` INT NOT NULL,
  `campus_id` INT NOT NULL,
  PRIMARY KEY (`id`, `campus_id`),
  INDEX `fk_edificio_utente1_idx` (`utente_id` ASC),
  INDEX `fk_edificio_campus1_idx` (`campus_id` ASC),
  CONSTRAINT `fk_edificio_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `indoorlocalizer`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_edificio_campus1`
    FOREIGN KEY (`campus_id`)
    REFERENCES `indoorlocalizer`.`campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`stanza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`stanza` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`stanza` (
  `nome` VARCHAR(255) NOT NULL,
  `piano` INT NULL,
  `informazioni_id` INT NULL,
  `utente_id` INT NOT NULL,
  `edificio_id` INT NOT NULL,
  `edificio_campus_id` INT NOT NULL,
  PRIMARY KEY (`nome`, `edificio_id`, `edificio_campus_id`),
  INDEX `fk_stanza_utente1_idx` (`utente_id` ASC),
  INDEX `fk_stanza_edificio1_idx` (`edificio_id` ASC, `edificio_campus_id` ASC),
  CONSTRAINT `fk_stanza_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `indoorlocalizer`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stanza_edificio1`
    FOREIGN KEY (`edificio_id` , `edificio_campus_id`)
    REFERENCES `indoorlocalizer`.`edificio` (`id` , `campus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`notifiche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`notifiche` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`notifiche` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dati` TEXT NULL,
  `utente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifiche_utente1_idx` (`utente_id` ASC),
  CONSTRAINT `fk_notifiche_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `indoorlocalizer`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`informazioni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`informazioni` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`informazioni` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dati` TEXT NULL,
  `utente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_informazioni_utente1_idx` (`utente_id` ASC),
  CONSTRAINT `fk_informazioni_utente1`
    FOREIGN KEY (`utente_id`)
    REFERENCES `indoorlocalizer`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`stanza_has_notifiche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`stanza_has_notifiche` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`stanza_has_notifiche` (
  `stanza_nome` VARCHAR(255) NOT NULL,
  `stanza_edificio_id` INT NOT NULL,
  `stanza_edificio_campus_id` INT NOT NULL,
  `notifiche_id` INT NOT NULL,
  PRIMARY KEY (`stanza_nome`, `stanza_edificio_id`, `stanza_edificio_campus_id`, `notifiche_id`),
  INDEX `fk_stanza_has_notifiche_notifiche1_idx` (`notifiche_id` ASC),
  INDEX `fk_stanza_has_notifiche_stanza1_idx` (`stanza_nome` ASC, `stanza_edificio_id` ASC, `stanza_edificio_campus_id` ASC),
  CONSTRAINT `fk_stanza_has_notifiche_stanza1`
    FOREIGN KEY (`stanza_nome` , `stanza_edificio_id` , `stanza_edificio_campus_id`)
    REFERENCES `indoorlocalizer`.`stanza` (`nome` , `edificio_id` , `edificio_campus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stanza_has_notifiche_notifiche1`
    FOREIGN KEY (`notifiche_id`)
    REFERENCES `indoorlocalizer`.`notifiche` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indoorlocalizer`.`ap_has_stanza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indoorlocalizer`.`ap_has_stanza` ;

CREATE TABLE IF NOT EXISTS `indoorlocalizer`.`ap_has_stanza` (
  `ap_mac` VARCHAR(255) NOT NULL,
  `stanza_nome` VARCHAR(255) NOT NULL,
  `stanza_edificio_id` INT NOT NULL,
  `stanza_edificio_campus_id` INT NOT NULL,
  PRIMARY KEY (`ap_mac`, `stanza_nome`, `stanza_edificio_id`, `stanza_edificio_campus_id`),
  INDEX `fk_ap_has_stanza_stanza1_idx` (`stanza_nome` ASC, `stanza_edificio_id` ASC, `stanza_edificio_campus_id` ASC),
  INDEX `fk_ap_has_stanza_ap1_idx` (`ap_mac` ASC),
  CONSTRAINT `fk_ap_has_stanza_ap1`
    FOREIGN KEY (`ap_mac`)
    REFERENCES `indoorlocalizer`.`ap` (`mac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ap_has_stanza_stanza1`
    FOREIGN KEY (`stanza_nome` , `stanza_edificio_id` , `stanza_edificio_campus_id`)
    REFERENCES `indoorlocalizer`.`stanza` (`nome` , `edificio_id` , `edificio_campus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
