package it.uni.pwm.indoorlocalizer.model.pojo;
// default package
// Generated 8-nov-2017 11.08.49 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ap generated by hbm2java
 */
public class Ap implements java.io.Serializable {

	private String mac;
	private Utente utente;
	private int canale;
	private String ssid;
	private Set stanzas = new HashSet(0);

	public Ap() {
	}

	public Ap(String mac, Utente utente, int canale, String ssid) {
		this.mac = mac;
		this.utente = utente;
		this.canale = canale;
		this.ssid = ssid;
	}

	public Ap(String mac, Utente utente, int canale, String ssid, Set stanzas) {
		this.mac = mac;
		this.utente = utente;
		this.canale = canale;
		this.ssid = ssid;
		this.stanzas = stanzas;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	public int getCanale() {
		return this.canale;
	}

	public void setCanale(int canale) {
		this.canale = canale;
	}

	public String getSsid() {
		return this.ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}

	public Set getStanzas() {
		return this.stanzas;
	}

	public void setStanzas(Set stanzas) {
		this.stanzas = stanzas;
	}

}
