package it.uni.pwm.indoorlocalizer.model.pojo;
// default package
// Generated 8-nov-2017 11.08.49 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Edificio generated by hbm2java
 */
public class Edificio implements java.io.Serializable {

	private EdificioId id;
	private Campus campus;
	private Utente utente;
	private String nome;
	private Set stanzas = new HashSet(0);

	public Edificio() {
	}

	public Edificio(EdificioId id, Campus campus, Utente utente, String nome) {
		this.id = id;
		this.campus = campus;
		this.utente = utente;
		this.nome = nome;
	}

	public Edificio(EdificioId id, Campus campus, Utente utente, String nome, Set stanzas) {
		this.id = id;
		this.campus = campus;
		this.utente = utente;
		this.nome = nome;
		this.stanzas = stanzas;
	}

	public EdificioId getId() {
		return this.id;
	}

	public void setId(EdificioId id) {
		this.id = id;
	}

	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getStanzas() {
		return this.stanzas;
	}

	public void setStanzas(Set stanzas) {
		this.stanzas = stanzas;
	}

}
