package it.uni.pwm.indoorlocalizer.model.pojo;
// default package
// Generated 8-nov-2017 11.08.49 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Notifiche generated by hbm2java
 */
public class Notifiche implements java.io.Serializable {

	private Integer id;
	private Utente utente;
	private String dati;
	private Set stanzas = new HashSet(0);

	public Notifiche() {
	}

	public Notifiche(Utente utente) {
		this.utente = utente;
	}

	public Notifiche(Utente utente, String dati, Set stanzas) {
		this.utente = utente;
		this.dati = dati;
		this.stanzas = stanzas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	public String getDati() {
		return this.dati;
	}

	public void setDati(String dati) {
		this.dati = dati;
	}

	public Set getStanzas() {
		return this.stanzas;
	}

	public void setStanzas(Set stanzas) {
		this.stanzas = stanzas;
	}

}
