package it.uni.pwm.indoorlocalizer.model;
// default package
// Generated 8-nov-2017 11.08.49 by Hibernate Tools 5.2.5.Final

/**
 * Informazioni generated by hbm2java
 */
public class Informazioni implements java.io.Serializable {

	private Integer id;
	private Utente utente;
	private String dati;

	public Informazioni() {
	}

	public Informazioni(Utente utente) {
		this.utente = utente;
	}

	public Informazioni(Utente utente, String dati) {
		this.utente = utente;
		this.dati = dati;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	public String getDati() {
		return this.dati;
	}

	public void setDati(String dati) {
		this.dati = dati;
	}

}
